#
# Github Actions for Serverless Framework
#
# Create AWS_KEY and AWS_SECRET secrets in Github repository settings
# If you're using env.yml file, store its content as ENV Github secret
#
# Master branch will be deployed as DEV and every new tag starting with "v**" (e.g. v1.0, v1.2, v2.0, etc) will be deployed as PROD
#
# Learn more: https://maxkostinevich.com/blog/how-to-deploy-serverless-applications-using-github-actions/
#

name: Deploy TO Staging

on:
  push:
    branches:
      - staging

permissions:
  id-token: write # This is required for requesting the JWT by GitHub for AWS access
  contents: read  # This is required for actions/checkout

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (to provide access to our code)
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: arn:aws:iam::979176640062:role/github-action-role
          aws-region: ap-south-1
          mask-aws-account-id: 'false'

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
          
      - name: Install Serverless Framework
        run: npm install -g serverless

      - name: Install Serverless Compose
        run: npm install -g @serverless/compose

      - name: Install Serverless Python Requirements Plugin
        run: npm install -g serverless-python-requirements

      - name: Install serverless plugins
        run: npm install serverless-offline -g

      - name: Create env file
        run: |
          cat > env.yml << EOF
          ${{ vars.ENV }}
          EOF

      - name: Create env file for secrets
        run: |
          cat > env_secrets.yml << EOF
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY_STAGING }}
          SUPABASE_JWT_SECRET: ${{ secrets.SUPABASE_JWT_SECRET_STAGING }}
          EOF

      - name: Deploy Lambda functions
        run: sls deploy --stage staging
        env:
          AWS_REGION: ap-south-1
